version: '3.9'

services:
  db:
    container_name: password_manager_pg
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: passmanager
      POSTGRES_PASSWORD: passmanagerjaya
      POSTGRES_DB: passmanagerDB
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
    ports:
      - 5432:5432

  db-test:
    container_name: password_manager_pg_test
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: passmanagerTest
      POSTGRES_PASSWORD: passmanagerjayaTest
      POSTGRES_DB: passmanagerDBTest
    volumes:
      - './tmp/db_test:/var/lib/postgresql/data'
    ports:
      - 5433:5432

  adminer:
    container_name: password_manager_adminer
    depends_on:
      - db
    links:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
